In [2]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [3]:
BASE_DIR = Path("..")

RAW_DATA_PATH = BASE_DIR / "data" / "raw" / "creepypastas.xlsx"

PROCESSED_DATA_PATH = BASE_DIR / "data" / "processed" / "creepypastas_clean.csv"

RAW_DATA_PATH

PosixPath('../data/raw/creepypastas.xlsx')

In [4]:
Path("..")

PosixPath('..')

In [5]:
if RAW_DATA_PATH.exists():
    print("Archivo encontrado correctamente.")
else:
    print("Archivo NO encontrado. Revisa que esté en data/raw/ y que se llame creepypastas.xlsx")

Archivo encontrado correctamente.

In [6]:
excel_file = pd.ExcelFile(RAW_DATA_PATH)

excel_file.sheet_names

['Sheet1']

In [7]:
sheet_name = excel_file.sheet_names[0]

df = pd.read_excel(RAW_DATA_PATH, sheet_name=sheet_name)

df.head()

,story_name,average_rating,tags,body,estimated_reading_time,publish_date,categories
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me",9.25,"drug trials, drugs, experimentation, experiments, madness, Peter Frost David, psychological, psychological horror, sci-fi, science, science fiction, time\n","If you’re armed and at the Glenmont metro, please shoot me.\nMake it a headshot. Shoot me in the temple, aiming slightly downwards. I need the bullet to travel the shortest possible distance throu...",12 minutes,"February 20, 2020","Drugs and Addictions, Madness, Paranoia, and Mental Illness, Psychological Horror, Science and Experimentation, Science Fiction and Aliens"
1,A Shattered Life,9.13,"disease, entities, Matt Dymerski, monsters, paranormal, supernatural, time travel\n","I don’t know when you’re going to read this, but I can tell you when it started: I was out for a walk alone in the woods when the entity came for me. It was beyond a blur. It was, for lack of a ...",14 minutes,"July 22, 2020","Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Science Fiction and Aliens"
2,My Father Punished Me When I Talked to Ghosts,9.12,"abductions, blindness, child abuse, childhood, children, crimes, deaths, deception, investigations, kidnappings, kids, lies, murders\n","I’ve been blind since birth. As I grew up, everything was described to me in such vivid detail that I didn’t even realize why it was that important to see, especially having no reference point to ...",8 minutes,"December 10, 2019","Abductions and Kidnappings, Children and Childhood, Deaths, Murders, and Disappearances, Investigations and Crimes"
3,Distorted Warning Signals,9.12,Ashley Rose Wellman\n,"When I got the first one, I was literally seconds away from stepping onto the plane when a call from “UNKNOWN” blared from my cell phone. It was a ringtone I hadn’t heard before, one I was pretty ...",3 minutes,"July 13, 2019","Beings and Entities, Deaths, Murders, and Disappearances, Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Occult, Magic, and Witchcraft, Psychological Horror, Survival H..."
4,He Who Wanders,9.12,Simon Simonian\n,"I missed the scorching wind of Andalusia. How it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. I missed the smell of the valley ...",22 minutes,"January 24, 2017",Beings and Entities

In [8]:
print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

df.columns

Filas: 3510
Columnas: 7

Index(['story_name', 'average_rating', 'tags', 'body',
       'estimated_reading_time', 'publish_date', 'categories'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3510 entries, 0 to 3509
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   story_name              3510 non-null   str
 1   average_rating          3510 non-null   float64
 2   tags                    2081 non-null   str
 3   body                    3510 non-null   str
 4   estimated_reading_time  3509 non-null   str
 5   publish_date            3510 non-null   str
 6   categories              3509 non-null   str
dtypes: float64(1), str(6)
memory usage: 192.1 KB

In [10]:
missing_values = df.isnull().sum().sort_values(ascending=False)

missing_values

tags                      1429
categories                   1
estimated_reading_time       1
average_rating               0
story_name                   0
body                         0
publish_date                 0
dtype: int64

In [11]:
duplicate_rows = df.duplicated().sum()

print("Filas duplicadas completas:", duplicate_rows)

Filas duplicadas completas: 0

In [12]:
df_clean = df.copy()

df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df_clean.columns

Index(['story_name', 'average_rating', 'tags', 'body',
       'estimated_reading_time', 'publish_date', 'categories'],
      dtype='str')

In [13]:
df_clean.head()

,story_name,average_rating,tags,body,estimated_reading_time,publish_date,categories
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me",9.25,"drug trials, drugs, experimentation, experiments, madness, Peter Frost David, psychological, psychological horror, sci-fi, science, science fiction, time\n","If you’re armed and at the Glenmont metro, please shoot me.\nMake it a headshot. Shoot me in the temple, aiming slightly downwards. I need the bullet to travel the shortest possible distance throu...",12 minutes,"February 20, 2020","Drugs and Addictions, Madness, Paranoia, and Mental Illness, Psychological Horror, Science and Experimentation, Science Fiction and Aliens"
1,A Shattered Life,9.13,"disease, entities, Matt Dymerski, monsters, paranormal, supernatural, time travel\n","I don’t know when you’re going to read this, but I can tell you when it started: I was out for a walk alone in the woods when the entity came for me. It was beyond a blur. It was, for lack of a ...",14 minutes,"July 22, 2020","Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Science Fiction and Aliens"
2,My Father Punished Me When I Talked to Ghosts,9.12,"abductions, blindness, child abuse, childhood, children, crimes, deaths, deception, investigations, kidnappings, kids, lies, murders\n","I’ve been blind since birth. As I grew up, everything was described to me in such vivid detail that I didn’t even realize why it was that important to see, especially having no reference point to ...",8 minutes,"December 10, 2019","Abductions and Kidnappings, Children and Childhood, Deaths, Murders, and Disappearances, Investigations and Crimes"
3,Distorted Warning Signals,9.12,Ashley Rose Wellman\n,"When I got the first one, I was literally seconds away from stepping onto the plane when a call from “UNKNOWN” blared from my cell phone. It was a ringtone I hadn’t heard before, one I was pretty ...",3 minutes,"July 13, 2019","Beings and Entities, Deaths, Murders, and Disappearances, Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Occult, Magic, and Witchcraft, Psychological Horror, Survival H..."
4,He Who Wanders,9.12,Simon Simonian\n,"I missed the scorching wind of Andalusia. How it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. I missed the smell of the valley ...",22 minutes,"January 24, 2017",Beings and Entities

In [14]:
possible_title_cols = [col for col in df_clean.columns if "title" in col or "name" in col]
possible_text_cols = [col for col in df_clean.columns if "text" in col or "story" in col or "body" in col or "content" in col]
possible_rating_cols = [col for col in df_clean.columns if "rating" in col or "score" in col or "rate" in col]

print("Posibles columnas de título:", possible_title_cols)
print("Posibles columnas de texto:", possible_text_cols)
print("Posibles columnas de rating:", possible_rating_cols)

Posibles columnas de título: ['story_name']
Posibles columnas de texto: ['story_name', 'body']
Posibles columnas de rating: ['average_rating']

In [15]:
df_project = df_clean[
    [
        "story_name",
        "average_rating",
        "tags",
        "body",
        "estimated_reading_time",
        "publish_date",
        "categories"
    ]
].copy()

# Rename columns to clearer project names
df_project = df_project.rename(columns={
    "story_name": "title",
    "average_rating": "rating",
    "body": "story_text"
})

df_project.head()

,title,rating,tags,story_text,estimated_reading_time,publish_date,categories
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me",9.25,"drug trials, drugs, experimentation, experiments, madness, Peter Frost David, psychological, psychological horror, sci-fi, science, science fiction, time\n","If you’re armed and at the Glenmont metro, please shoot me.\nMake it a headshot. Shoot me in the temple, aiming slightly downwards. I need the bullet to travel the shortest possible distance throu...",12 minutes,"February 20, 2020","Drugs and Addictions, Madness, Paranoia, and Mental Illness, Psychological Horror, Science and Experimentation, Science Fiction and Aliens"
1,A Shattered Life,9.13,"disease, entities, Matt Dymerski, monsters, paranormal, supernatural, time travel\n","I don’t know when you’re going to read this, but I can tell you when it started: I was out for a walk alone in the woods when the entity came for me. It was beyond a blur. It was, for lack of a ...",14 minutes,"July 22, 2020","Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Science Fiction and Aliens"
2,My Father Punished Me When I Talked to Ghosts,9.12,"abductions, blindness, child abuse, childhood, children, crimes, deaths, deception, investigations, kidnappings, kids, lies, murders\n","I’ve been blind since birth. As I grew up, everything was described to me in such vivid detail that I didn’t even realize why it was that important to see, especially having no reference point to ...",8 minutes,"December 10, 2019","Abductions and Kidnappings, Children and Childhood, Deaths, Murders, and Disappearances, Investigations and Crimes"
3,Distorted Warning Signals,9.12,Ashley Rose Wellman\n,"When I got the first one, I was literally seconds away from stepping onto the plane when a call from “UNKNOWN” blared from my cell phone. It was a ringtone I hadn’t heard before, one I was pretty ...",3 minutes,"July 13, 2019","Beings and Entities, Deaths, Murders, and Disappearances, Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Occult, Magic, and Witchcraft, Psychological Horror, Survival H..."
4,He Who Wanders,9.12,Simon Simonian\n,"I missed the scorching wind of Andalusia. How it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. I missed the smell of the valley ...",22 minutes,"January 24, 2017",Beings and Entities

In [16]:
print("Rows:", df_project.shape[0])
print("Columns:", df_project.shape[1])

df_project.columns

Rows: 3510
Columns: 7

Index(['title', 'rating', 'tags', 'story_text', 'estimated_reading_time',
       'publish_date', 'categories'],
      dtype='str')

In [17]:
df_project.isnull().sum()

title                        0
rating                       0
tags                      1429
story_text                   0
estimated_reading_time       1
publish_date                 0
categories                   1
dtype: int64

In [18]:
df_project["tags"] = df_project["tags"].fillna("no_tags")
df_project["categories"] = df_project["categories"].fillna("uncategorized")
df_project["estimated_reading_time"] = df_project["estimated_reading_time"].fillna("unknown")

df_project["title"] = df_project["title"].fillna("Untitled")
df_project["title"] = df_project["title"].astype(str).str.strip()

df_project["story_text"] = df_project["story_text"].astype(str).str.strip()
df_project = df_project[df_project["story_text"] != ""]

df_project["tags"] = (
    df_project["tags"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace("Please wait...", "", regex=False)
    .str.strip()
)

df_project["categories"] = (
    df_project["categories"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace("Please wait...", "", regex=False)
    .str.strip()
)

df_project["tags"] = df_project["tags"].replace("", "no_tags")
df_project["categories"] = df_project["categories"].replace("", "uncategorized")

df_project.isnull().sum()

title                     0
rating                    0
tags                      0
story_text                0
estimated_reading_time    0
publish_date              0
categories                0
dtype: int64

In [19]:
df_project["rating_numeric"] = pd.to_numeric(df_project["rating"], errors="coerce")

invalid_ratings = df_project["rating_numeric"].isnull().sum()

print("Invalid ratings or empty:", invalid_ratings)

Invalid ratings or empty: 0

In [20]:
df_project["rating_numeric"].describe()

count    3510.000000
mean        7.565046
std         1.132757
min         0.860000
25%         6.980000
50%         7.790000
75%         8.420000
max         9.250000
Name: rating_numeric, dtype: float64

In [21]:
df_project["story_length_chars"] = df_project["story_text"].str.len()
df_project["word_count"] = df_project["story_text"].str.split().str.len()

df_project[["title", "rating_numeric", "story_length_chars", "word_count"]].head()

,title,rating_numeric,story_length_chars,word_count
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me",9.25,19493,3560
1,A Shattered Life,9.13,20837,3919
2,My Father Punished Me When I Talked to Ghosts,9.12,10859,2135
3,Distorted Warning Signals,9.12,4150,768
4,He Who Wanders,9.12,32767,6021

In [22]:
short_stories = df_project[df_project["word_count"] < 50]

print("Stories with less than 50 words:", short_stories.shape[0])

short_stories[["title", "word_count", "story_text"]].head()

Stories with less than 50 words: 28

,title,word_count,story_text
90,Too Long at the Cliff,6,Estimated reading time — 15 minute
150,"I’m a Cop, and I Institutionalized Someone I Knew Wasn’t Crazy",1,Part
180,The Man Who Returned,6,Estimated reading time — 19 minute
186,Darkstar,6,Estimated reading time — 57 minute
375,Tales From an Ex-Convict,1,Part

In [23]:
before = df_project.shape[0]

df_project = df_project[df_project["word_count"] >= 50]

after = df_project.shape[0]

print("Rows before filtering:", before)
print("Rows after filtering:", after)
print("Rows removed:", before - after)

Rows before filtering: 3510
Rows after filtering: 3482
Rows removed: 28

In [24]:
before = df_project.shape[0]

df_project = df_project.drop_duplicates(subset=["story_text"])

after = df_project.shape[0]

print("Rows before removing duplicates:", before)
print("Rows after removing duplicates:", after)
print("Duplicates removed:", before - after)

Rows before removing duplicates: 3482
Rows after removing duplicates: 3478
Duplicates removed: 4

In [25]:
df_project["text_lower"] = df_project["story_text"].str.lower()

df_project[["title", "text_lower"]].head()

,title,text_lower
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me","if you’re armed and at the glenmont metro, please shoot me.\nmake it a headshot. shoot me in the temple, aiming slightly downwards. i need the bullet to travel the shortest possible distance throu..."
1,A Shattered Life,"i don’t know when you’re going to read this, but i can tell you when it started: i was out for a walk alone in the woods when the entity came for me. it was beyond a blur. it was, for lack of a be..."
2,My Father Punished Me When I Talked to Ghosts,"i’ve been blind since birth. as i grew up, everything was described to me in such vivid detail that i didn’t even realize why it was that important to see, especially having no reference point to ..."
3,Distorted Warning Signals,"when i got the first one, i was literally seconds away from stepping onto the plane when a call from “unknown” blared from my cell phone. it was a ringtone i hadn’t heard before, one i was pretty ..."
4,He Who Wanders,"i missed the scorching wind of andalusia. how it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. i missed the smell of the valley ..."

In [26]:
df_project["publish_date"] = pd.to_datetime(df_project["publish_date"], errors="coerce")

df_project[["title", "publish_date"]].head()

                                                        title publish_date
0  If You’re Armed and at the Glenmont Metro, Please Shoot Me   2020-02-20
1                                            A Shattered Life   2020-07-22
2               My Father Punished Me When I Talked to Ghosts   2019-12-10
3                                   Distorted Warning Signals   2019-07-13
4                                              He Who Wanders   2017-01-24

In [27]:
df_project = df_project[
    [
        "title",
        "story_text",
        "text_lower",
        "rating",
        "rating_numeric",
        "story_length_chars",
        "word_count",
        "tags",
        "categories",
        "estimated_reading_time",
        "publish_date"
    ]
]

df_project = df_project.reset_index(drop=True)

df_project.head()

,title,story_text,text_lower,rating,rating_numeric,story_length_chars,word_count,tags,categories,estimated_reading_time,publish_date
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me","If you’re armed and at the Glenmont metro, please shoot me.\nMake it a headshot. Shoot me in the temple, aiming slightly downwards. I need the bullet to travel the shortest possible distance throu...","if you’re armed and at the glenmont metro, please shoot me.\nmake it a headshot. shoot me in the temple, aiming slightly downwards. i need the bullet to travel the shortest possible distance throu...",9.25,9.25,19493,3560,"drug trials, drugs, experimentation, experiments, madness, Peter Frost David, psychological, psychological horror, sci-fi, science, science fiction, time","Drugs and Addictions, Madness, Paranoia, and Mental Illness, Psychological Horror, Science and Experimentation, Science Fiction and Aliens",12 minutes,2020-02-20
1,A Shattered Life,"I don’t know when you’re going to read this, but I can tell you when it started: I was out for a walk alone in the woods when the entity came for me. It was beyond a blur. It was, for lack of a be...","i don’t know when you’re going to read this, but i can tell you when it started: i was out for a walk alone in the woods when the entity came for me. it was beyond a blur. it was, for lack of a be...",9.13,9.13,20837,3919,"disease, entities, Matt Dymerski, monsters, paranormal, supernatural, time travel","Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Science Fiction and Aliens",14 minutes,2020-07-22
2,My Father Punished Me When I Talked to Ghosts,"I’ve been blind since birth. As I grew up, everything was described to me in such vivid detail that I didn’t even realize why it was that important to see, especially having no reference point to ...","i’ve been blind since birth. as i grew up, everything was described to me in such vivid detail that i didn’t even realize why it was that important to see, especially having no reference point to ...",9.12,9.12,10859,2135,"abductions, blindness, child abuse, childhood, children, crimes, deaths, deception, investigations, kidnappings, kids, lies, murders","Abductions and Kidnappings, Children and Childhood, Deaths, Murders, and Disappearances, Investigations and Crimes",8 minutes,2019-12-10
3,Distorted Warning Signals,"When I got the first one, I was literally seconds away from stepping onto the plane when a call from “UNKNOWN” blared from my cell phone. It was a ringtone I hadn’t heard before, one I was pretty ...","when i got the first one, i was literally seconds away from stepping onto the plane when a call from “unknown” blared from my cell phone. it was a ringtone i hadn’t heard before, one i was pretty ...",9.12,9.12,4150,768,Ashley Rose Wellman,"Beings and Entities, Deaths, Murders, and Disappearances, Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Occult, Magic, and Witchcraft, Psychological Horror, Survival Ho...",3 minutes,2019-07-13
4,He Who Wanders,"I missed the scorching wind of Andalusia. How it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. I missed the smell of the valley ...","i missed the scorching wind of andalusia. how it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. i missed the smell of the valley ...",9.12,9.12,32767,6021,Simon Simonian,Beings and Entities,22 minutes,2017-01-24

In [28]:
print("Final rows:", df_project.shape[0])
print("Final columns:", df_project.shape[1])

df_project.info()

Final rows: 3478
Final columns: 11
<class 'pandas.DataFrame'>
RangeIndex: 3478 entries, 0 to 3477
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   3478 non-null   str
 1   story_text              3478 non-null   str
 2   text_lower              3478 non-null   str
 3   rating                  3478 non-null   float64
 4   rating_numeric          3478 non-null   float64
 5   story_length_chars      3478 non-null   int64
 6   word_count              3478 non-null   int64
 7   tags                    3478 non-null   str
 8   categories              3478 non-null   str
 9   estimated_reading_time  3478 non-null   str
 10  publish_date            3478 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(6)
memory usage: 299.0 KB

In [29]:
df_project.isnull().sum()

title                     0
story_text                0
text_lower                0
rating                    0
rating_numeric            0
story_length_chars        0
word_count                0
tags                      0
categories                0
estimated_reading_time    0
publish_date              0
dtype: int64

In [30]:
PROCESSED_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)

df_project.to_csv(PROCESSED_DATA_PATH, index=False, encoding="utf-8")

print("Clean file saved in:")
print(PROCESSED_DATA_PATH)

Clean file saved in:
../data/processed/creepypastas_clean.csv

In [69]:
df_project.isnull().sum()

title                     0
story_text                0
text_lower                0
rating                    0
rating_numeric            0
story_length_chars        0
word_count                0
tags                      0
categories                0
estimated_reading_time    0
publish_date              0
dtype: int64

In [33]:
df_project["tags"] = df_project["tags"].fillna("no_tags")
df_project["categories"] = df_project["categories"].fillna("uncategorized")
df_project["estimated_reading_time"] = df_project["estimated_reading_time"].fillna("unknown")

df_project.isnull().sum()

title                     0
story_text                0
text_lower                0
rating                    0
rating_numeric            0
story_length_chars        0
word_count                0
tags                      0
categories                0
estimated_reading_time    0
publish_date              0
dtype: int64

In [34]:
df_project["rating"].head(20)

0     9.25
1     9.13
2     9.12
3     9.12
4     9.12
5     9.12
6     9.12
7     9.11
8     9.11
9     9.11
10    9.11
11    9.10
12    9.10
13    9.10
14    9.10
15    9.10
16    9.10
17    9.10
18    9.10
19    9.10
Name: rating, dtype: float64

In [35]:
df_project["rating_numeric"] = pd.to_numeric(df_project["rating"], errors="coerce")

invalid_ratings = df_project["rating_numeric"].isnull().sum()

print("Invalid Ratings or empty:", invalid_ratings)

Invalid Ratings or empty: 0

In [36]:
df_project["rating_numeric"].describe()

count    3478.000000
mean        7.566472
std         1.132679
min         0.860000
25%         6.980000
50%         7.790000
75%         8.420000
max         9.250000
Name: rating_numeric, dtype: float64

In [37]:
df_project["story_length_chars"] = df_project["story_text"].str.len()

df_project["word_count"] = df_project["story_text"].str.split().str.len()

df_project[["title", "rating_numeric", "story_length_chars", "word_count"]].head()

,title,rating_numeric,story_length_chars,word_count
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me",9.25,19493,3560
1,A Shattered Life,9.13,20837,3919
2,My Father Punished Me When I Talked to Ghosts,9.12,10859,2135
3,Distorted Warning Signals,9.12,4150,768
4,He Who Wanders,9.12,32767,6021

In [38]:
short_stories = df_project[df_project["word_count"] < 50]

print("Stories with less than 50 words:", short_stories.shape[0])

short_stories[["title", "word_count", "story_text"]].head()

Stories with less than 50 words: 0

Empty DataFrame
Columns: [title, word_count, story_text]
Index: []

In [39]:
df_project["text_lower"] = df_project["story_text"].str.lower()

df_project[["title", "text_lower"]].head()

,title,text_lower
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me","if you’re armed and at the glenmont metro, please shoot me.\nmake it a headshot. shoot me in the temple, aiming slightly downwards. i need the bullet to travel the shortest possible distance throu..."
1,A Shattered Life,"i don’t know when you’re going to read this, but i can tell you when it started: i was out for a walk alone in the woods when the entity came for me. it was beyond a blur. it was, for lack of a be..."
2,My Father Punished Me When I Talked to Ghosts,"i’ve been blind since birth. as i grew up, everything was described to me in such vivid detail that i didn’t even realize why it was that important to see, especially having no reference point to ..."
3,Distorted Warning Signals,"when i got the first one, i was literally seconds away from stepping onto the plane when a call from “unknown” blared from my cell phone. it was a ringtone i hadn’t heard before, one i was pretty ..."
4,He Who Wanders,"i missed the scorching wind of andalusia. how it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. i missed the smell of the valley ..."

In [40]:
df_project["publish_date"] = pd.to_datetime(df_project["publish_date"], errors="coerce")

df_project[["title", "publish_date"]].head()

                                                        title publish_date
0  If You’re Armed and at the Glenmont Metro, Please Shoot Me   2020-02-20
1                                            A Shattered Life   2020-07-22
2               My Father Punished Me When I Talked to Ghosts   2019-12-10
3                                   Distorted Warning Signals   2019-07-13
4                                              He Who Wanders   2017-01-24

In [41]:
df_project = df_project[
    [
        "title",
        "story_text",
        "text_lower",
        "rating",
        "rating_numeric",
        "story_length_chars",
        "word_count",
        "tags",
        "categories",
        "estimated_reading_time",
        "publish_date"
    ]
]

df_project.head()

,title,story_text,text_lower,rating,rating_numeric,story_length_chars,word_count,tags,categories,estimated_reading_time,publish_date
0,"If You’re Armed and at the Glenmont Metro, Please Shoot Me","If you’re armed and at the Glenmont metro, please shoot me.\nMake it a headshot. Shoot me in the temple, aiming slightly downwards. I need the bullet to travel the shortest possible distance throu...","if you’re armed and at the glenmont metro, please shoot me.\nmake it a headshot. shoot me in the temple, aiming slightly downwards. i need the bullet to travel the shortest possible distance throu...",9.25,9.25,19493,3560,"drug trials, drugs, experimentation, experiments, madness, Peter Frost David, psychological, psychological horror, sci-fi, science, science fiction, time","Drugs and Addictions, Madness, Paranoia, and Mental Illness, Psychological Horror, Science and Experimentation, Science Fiction and Aliens",12 minutes,2020-02-20
1,A Shattered Life,"I don’t know when you’re going to read this, but I can tell you when it started: I was out for a walk alone in the woods when the entity came for me. It was beyond a blur. It was, for lack of a be...","i don’t know when you’re going to read this, but i can tell you when it started: i was out for a walk alone in the woods when the entity came for me. it was beyond a blur. it was, for lack of a be...",9.13,9.13,20837,3919,"disease, entities, Matt Dymerski, monsters, paranormal, supernatural, time travel","Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Science Fiction and Aliens",14 minutes,2020-07-22
2,My Father Punished Me When I Talked to Ghosts,"I’ve been blind since birth. As I grew up, everything was described to me in such vivid detail that I didn’t even realize why it was that important to see, especially having no reference point to ...","i’ve been blind since birth. as i grew up, everything was described to me in such vivid detail that i didn’t even realize why it was that important to see, especially having no reference point to ...",9.12,9.12,10859,2135,"abductions, blindness, child abuse, childhood, children, crimes, deaths, deception, investigations, kidnappings, kids, lies, murders","Abductions and Kidnappings, Children and Childhood, Deaths, Murders, and Disappearances, Investigations and Crimes",8 minutes,2019-12-10
3,Distorted Warning Signals,"When I got the first one, I was literally seconds away from stepping onto the plane when a call from “UNKNOWN” blared from my cell phone. It was a ringtone I hadn’t heard before, one I was pretty ...","when i got the first one, i was literally seconds away from stepping onto the plane when a call from “unknown” blared from my cell phone. it was a ringtone i hadn’t heard before, one i was pretty ...",9.12,9.12,4150,768,Ashley Rose Wellman,"Beings and Entities, Deaths, Murders, and Disappearances, Madness, Paranoia, and Mental Illness, Monsters, Creatures, and Cryptids, Occult, Magic, and Witchcraft, Psychological Horror, Survival Ho...",3 minutes,2019-07-13
4,He Who Wanders,"I missed the scorching wind of Andalusia. How it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. I missed the smell of the valley ...","i missed the scorching wind of andalusia. how it pours sunlight onto your face, toying with eyelashes, flattening dry sand against cheeks and milling around hair. i missed the smell of the valley ...",9.12,9.12,32767,6021,Simon Simonian,Beings and Entities,22 minutes,2017-01-24

In [42]:
print("Last rows:", df_project.shape[0])
print("Final columns:", df_project.shape[1])

df_project.info()

Last rows: 3478
Final columns: 11
<class 'pandas.DataFrame'>
RangeIndex: 3478 entries, 0 to 3477
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   3478 non-null   str
 1   story_text              3478 non-null   str
 2   text_lower              3478 non-null   str
 3   rating                  3478 non-null   float64
 4   rating_numeric          3478 non-null   float64
 5   story_length_chars      3478 non-null   int64
 6   word_count              3478 non-null   int64
 7   tags                    3478 non-null   str
 8   categories              3478 non-null   str
 9   estimated_reading_time  3478 non-null   str
 10  publish_date            3478 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(6)
memory usage: 299.0 KB

In [43]:
df_project.isnull().sum()

title                     0
story_text                0
text_lower                0
rating                    0
rating_numeric            0
story_length_chars        0
word_count                0
tags                      0
categories                0
estimated_reading_time    0
publish_date              0
dtype: int64

In [44]:
PROCESSED_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)

df_project.to_csv(PROCESSED_DATA_PATH, index=False, encoding="utf-8")

print("Archivo limpio guardado en:")
print(PROCESSED_DATA_PATH)

Archivo limpio guardado en:
../data/processed/creepypastas_clean.csv

In [45]:
df_check = pd.read_csv(PROCESSED_DATA_PATH)

df_check.head()

df_check.info()

<class 'pandas.DataFrame'>
RangeIndex: 3478 entries, 0 to 3477
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   3478 non-null   str
 1   story_text              3478 non-null   str
 2   text_lower              3478 non-null   str
 3   rating                  3478 non-null   float64
 4   rating_numeric          3478 non-null   float64
 5   story_length_chars      3478 non-null   int64
 6   word_count              3478 non-null   int64
 7   tags                    3478 non-null   str
 8   categories              3478 non-null   str
 9   estimated_reading_time  3478 non-null   str
 10  publish_date            3478 non-null   str
dtypes: float64(2), int64(2), str(7)
memory usage: 299.0 KB